version: '3.8'

services:
  daemon:
    build: .
    container_name: secure-file-daemon
    restart: always
    volumes:
      - ./:/app   # Mount local source for easy development
    environment:
      - GOOGLE_OAUTH_CREDENTIALS=/app/credentials.json
    ports:
      - "8080:8080" # Optional if your daemon listens on ports
