version: '3.8'

services:
  daemon:
    build: .
    container_name: secure-file-daemon
    restart: always
    volumes:
      - ./local_sync:/sync  # Host folder for decrypted files
    secrets:
      - gdrive-creds

secrets:
  gdrive-creds:
    file: ./secrets/gdrive-creds.json  # Place your Google credentials here
